mysite/ans/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # /
    url(r'^$', views.index, name='index'),
    url(r'^add-question/$', views.question_create_view, name='question_add'),

    # /ans/question/1
    url(r'^question/(?P<question_id>[0-9]+)/$', views.detail, name='detail'),

    # /ans/question/userid
    url(r'^question/user/(?P<userid>[0-9]+)/$', views.asked_by_me, name='asked_by_me'),

    # /ans/answer/username
    url(r'^answer/user/(?P<userid>[0-9]+)/$', views.answered_by_me, name='answered_by_me'),

    url(r'^upvote/user/(?P<userid>[0-9]+)/$', views.upvoted_by_me, name='upvoted_by_me'),

    # /question/hour
    url(r'^question/hour/$', views.question_of_hour, name='question_of_hour'),
    url(r'^question/site/$', views.question_of_the_site, name='question_of_site'),

    # url(r'^answer/(?P<answer_id>[0-9]+)/votes$', views.vote, name='vote'),

]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import logout
from account.views import custom_login, register
from django.contrib.auth.views import LoginView

urlpatterns = [
    url(r'^login/$',LoginView.as_view(redirect_authenticated_user=True, template_name='account/login.html'),name='login'),
    url(r'^register/$', register, name='register'),
    url(r'^logout/$', logout,
        {'template_name': 'account/logged_out.html'}, name='logout'),

    url(r'^admin/', admin.site.urls),
    url(r'^', include('ans.urls', namespace='ans')),
    url(r'^profile/', include('account.urls', namespace='account')),
]

mysite/templates/snippets/css.html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

mysite/templates/snippets/js.html
<!-- Latest compiled and minified JavaScript -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

mysite/templates/snippets/nav.html
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!--Logo -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mainNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{% url 'ans:index'  %}" class="navbar-brand">MySite</a>
        </div>

        <div class="collapse navbar-collapse" id="mainNavBar">

            <ul class="nav navbar-nav">
                <li><a href="{% url 'ans:index' %}">Home</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Contact</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">View Options <span
                            class="caret"></span> </a>
                    <ul class="dropdown-menu">
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'ans:asked_by_me' user.id %}">Asked by Me</a></li>
                        <li><a href="{% url 'ans:answered_by_me' user.id %}">Answered by me</a></li>
                        <li><a href="{% url 'ans:upvoted_by_me' user.id %}">Upvoted ans by me</a></li>
                        {% endif %}
                        <li><a href="{% url 'ans:question_of_hour' %}">Question of the hour</a></li>
                        <li><a href="{% url 'ans:question_of_site' %}">Question of the site</a></li>
                    </ul>
                </li>
            </ul>


            <div class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}">{{ user }} Logout <span
                        class=" glyphicon glyphicon-log-out"></span></a></li>
                {% else %}

                <li><a href="{% url 'register' %}">SignUp <span
                        class=" glyphicon glyphicon-registration-mark"></span></a></li>

                <li><a href="{% url 'login' %}">Login <span
                        class=" glyphicon glyphicon-log-in"></span></a></li>
                {% endif %}
            </div>
        </div>

    </div>
</nav>